const RECORD_KEY="ai-exam-coach-records-v6";
const IMPORT_KEY="ai-exam-coach-imported-bank-v1";
let questionBank=[];
let serverQuestions=[];
let activeCategory="全部";
let activeExam="全部";
let activeType="全部";
let activeDifficulty="全部";
let activeIndex=0;
let selectedOption="";
let latestMarkdown="";

const samples={
  civil:["考公","行测-判断推理","某单位要从甲、乙、丙、丁四人中选两人参加培训。已知：如果选甲，就必须选乙；如果不选丙，就不能选丁。现在已经确定不选乙。问以下哪项一定为真？A. 不选甲 B. 选丙 C. 不选丁 D. 选甲","C","A","我觉得既然不选乙，根据如果选甲就必须选乙，所以应该不选甲。但题目问一定为真，我又看到不选丙就不能选丁，所以我感觉不选丁也可能成立，于是选了 C。"],
  public:["事业编/考编","公共基础知识","行政处罚与行政强制的主要区别是什么？A. 行政处罚重在惩戒违法行为 B. 二者都只能由法院实施 C. 行政强制一定是罚款 D. 行政处罚不需要法律依据","C","A","我看到强制两个字，就想到强制交钱，所以觉得行政强制就是罚款。"],
  teacher:["教师资格证","教育知识与能力","学生通过观察教师示范后学会某种行为，这主要体现了哪种学习理论？A. 经典条件反射 B. 操作性条件反射 C. 社会学习理论 D. 认知结构学习理论","B","C","我觉得学生学会行为，应该是强化形成的，所以选了操作性条件反射。"],
  essay:["考公","申论/主观题","请根据材料，概括基层治理中群众参与不足的主要原因。","群众参与不足主要是因为群众素质不高、基层工作宣传不到位。","","我先找材料里出现频率高的词，然后把原因归纳为群众和基层两个方面。"],
  custom:["其他考试","公共基础知识","","", "", ""]
};

const fallbackQuestions=[{
  id:"civil-logic-1",category:"公职类",examType:"考公",subject:"行测-判断推理",chapter:"翻译推理",knowledgePoint:"逆否命题",type:"单选题",difficulty:"基础",
  stem:"如果某人参加甲项目，就必须参加乙项目。现在小王没有参加乙项目。以下哪项一定为真？",
  options:["小王参加了甲项目","小王没有参加甲项目","小王参加了乙项目","不能判断小王是否参加甲项目"],answer:"B",
  explanation:"题干是“甲 -> 乙”。已知“非乙”，根据逆否命题可推出“非甲”。",
  tags:["逻辑判断"],sourceType:"自建题库",source:"产品内置原创示例题",licenseNote:"原创示例题，可用于产品演示。"
}];

function $(id){return document.getElementById(id)}
function esc(text){return String(text||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function icons(){if(window.lucide)window.lucide.createIcons()}
function toast(text){const el=$("toast");if(!el)return;el.textContent=text;el.classList.add("show");setTimeout(()=>el.classList.remove("show"),1800)}
function getImported(){try{const items=JSON.parse(localStorage.getItem(IMPORT_KEY)||"[]");return Array.isArray(items)?items:[]}catch{return[]}}
function setImported(items){localStorage.setItem(IMPORT_KEY,JSON.stringify(items));renderImportSummary()}
function normalize(item,index=0){
  const options=Array.isArray(item.options)?item.options:String(item.options||"").split("|").map(x=>x.trim()).filter(Boolean);
  return {id:String(item.id||`import-${Date.now()}-${index}`).trim(),category:String(item.category||"").trim(),examType:String(item.examType||item.exam||"").trim(),subject:String(item.subject||"").trim(),chapter:String(item.chapter||"综合").trim(),knowledgePoint:String(item.knowledgePoint||item.knowledge||"").trim(),type:String(item.type||"单选题").trim(),difficulty:String(item.difficulty||"基础").trim(),stem:String(item.stem||item.question||"").trim(),options,answer:String(item.answer||"").trim().toUpperCase(),explanation:String(item.explanation||"").trim(),tags:Array.isArray(item.tags)?item.tags:String(item.tags||"").split("|").map(x=>x.trim()).filter(Boolean),sourceType:String(item.sourceType||"自建题库").trim(),source:String(item.source||"").trim(),licenseNote:String(item.licenseNote||item.license||"").trim()}
}
function validate(q){const miss=[];["category","examType","subject","type","difficulty","stem","answer","explanation","sourceType","source","licenseNote"].forEach(k=>{if(!q[k])miss.push(k)});if(!Array.isArray(q.options)||q.options.length<2)miss.push("options");if(q.type==="单选题"&&!/^[A-Z]$/.test(q.answer))miss.push("answer格式");return miss}
function mergeBanks(base){const merged=[...base];[...serverQuestions,...getImported()].forEach(q=>{const i=merged.findIndex(x=>x.id===q.id);if(i>=0)merged[i]=q;else merged.push(q)});return merged}

function injectV6(){
  const metrics=document.querySelectorAll(".metric-row strong");if(metrics[0])metrics[0].textContent="v0.6";if(metrics[1])metrics[1].textContent="云端题库";
  const pill=document.querySelector(".status-pill");if(pill)pill.innerHTML='<i data-lucide="cloud-upload"></i> 云端题库版';
  const road=document.querySelector(".agent-roadmap p");if(road)road.textContent="当前是 AI 学考教练 v0.6：支持题库导入、管理员发布到服务器、所有用户共享云端题库。";
  const steps=document.querySelector(".roadmap-steps");if(steps&&!steps.textContent.includes("v0.6"))steps.insertAdjacentHTML("beforeend",'<span class="done">v0.5 批量导入</span><span class="done">v0.6 云端题库</span>');
  const bank=document.querySelector(".bank-panel");
  if(bank&&!$("questionImportFile"))bank.insertAdjacentHTML("afterend",`<section class="panel import-panel" aria-label="题库导入后台">
    <div class="records-header"><div><strong><i data-lucide="file-up"></i> 题库导入后台</strong><p>支持 JSON/CSV 批量导入；导入后可用管理员口令发布到服务器。</p></div><div class="bank-counter"><span id="importedCount">0</span> 题已导入</div></div>
    <div class="import-grid"><label class="field import-file"><span><i data-lucide="upload-cloud"></i> 选择题库文件</span><input id="questionImportFile" type="file" accept=".json,.csv,application/json,text/csv" /></label><div class="btn-row"><button class="btn primary" type="button" id="importQuestionsBtn"><i data-lucide="file-check-2"></i> 导入题库</button><button class="btn" type="button" id="downloadTemplateBtn"><i data-lucide="file-down"></i> 下载模板</button><button class="btn" type="button" id="exportBankBtn"><i data-lucide="download"></i> 导出题库</button><button class="btn danger" type="button" id="clearImportedBankBtn"><i data-lucide="eraser"></i> 清空导入</button></div></div>
    <div class="import-grid server-publish-grid"><label class="field"><span><i data-lucide="key-round"></i> 管理员口令</span><input id="adminTokenInput" type="password" placeholder="填写服务器 ADMIN_TOKEN" /></label><div class="btn-row"><button class="btn primary" type="button" id="publishServerBankBtn"><i data-lucide="cloud-upload"></i> 发布到服务器</button><button class="btn" type="button" id="refreshServerBankBtn"><i data-lucide="refresh-cw"></i> 刷新云端题库</button><span class="tag">服务器题库 <strong id="serverBankCount">0</strong> 题</span></div></div>
    <div class="source-note" id="importStatus">等待选择题库文件。必填：分类、考试、科目、题型、题干、选项、答案、解析、来源和版权说明。</div><div class="import-preview" id="importPreview"></div>
  </section>`);
  if(!$("generateSimilarBtn"))document.querySelector("#practiceCard .btn-row")?.insertAdjacentHTML("beforeend",'<button class="btn" type="button" id="generateSimilarBtn"><i data-lucide="copy-plus"></i> 生成同类题</button>');
  if(!$("v6Style")){const style=document.createElement("style");style.id="v6Style";style.textContent='.import-panel{margin-bottom:18px;padding:15px;display:grid;gap:14px}.import-grid{display:grid;grid-template-columns:minmax(220px,1fr) auto;gap:12px;align-items:end}.import-file input{min-height:42px;padding:9px}.import-preview{display:grid;gap:8px}.import-item{padding:10px;border:1px solid var(--line);border-radius:var(--radius);background:#fbfdfc}.import-item strong{display:block;font-size:13px}.import-item p{margin:5px 0;color:#42504d;font-size:12px;line-height:1.5}.import-item span{color:var(--muted);font-size:12px}.source-note{padding:9px 10px;border-radius:8px;border:1px solid #f1d59f;background:#fff3d8;color:#6d4508;font-size:12px;line-height:1.5}.bank-filters{display:grid;gap:10px}.bank-category-row{display:flex;gap:8px;overflow-x:auto}.bank-select-row{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.bank-select{display:grid;gap:5px}.bank-select span{color:#667371;font-size:12px;font-weight:800}@media(max-width:780px){.import-grid,.bank-select-row{grid-template-columns:1fr}}';document.head.appendChild(style)}
}

async function loadServerBank(){try{const res=await fetch("/api/question-bank",{cache:"no-store"});if(!res.ok)throw new Error();const data=await res.json();serverQuestions=Array.isArray(data.questions)?data.questions.map(normalize):[]}catch{serverQuestions=[]}if($("serverBankCount"))$("serverBankCount").textContent=String(serverQuestions.length)}
async function loadBank(){await loadServerBank();try{const res=await fetch("data/questions.json",{cache:"no-store"});const data=await res.json();questionBank=mergeBanks((data.questions||[]).map(normalize))}catch{questionBank=mergeBanks(fallbackQuestions.map(normalize));toast("题库文件未加载，已使用备用题库")}renderFilters();renderQuestion();renderImportSummary()}
function filtered(){return questionBank.filter(q=>(activeCategory==="全部"||q.category===activeCategory)&&(activeExam==="全部"||q.examType===activeExam)&&(activeType==="全部"||(q.type||"单选题")===activeType)&&(activeDifficulty==="全部"||q.difficulty===activeDifficulty))}
function activeQuestion(){const list=filtered();return list[activeIndex%Math.max(list.length,1)]||questionBank[0]}
function select(label,key,value,options){return `<label class="bank-select"><span>${label}</span><select data-filter="${key}">${options.map(x=>`<option value="${esc(x)}" ${x===value?"selected":""}>${esc(x)}</option>`).join("")}</select></label>`}
function renderFilters(){const cats=["全部",...new Set(questionBank.map(q=>q.category))];const exams=["全部",...new Set(questionBank.map(q=>q.examType))];const types=["全部",...new Set(questionBank.map(q=>q.type||"单选题"))];const diffs=["全部",...new Set(questionBank.map(q=>q.difficulty))];$("bankFilters").innerHTML=`<div class="bank-category-row">${cats.map(c=>`<button class="bank-filter ${c===activeCategory?"active":""}" type="button" data-category="${esc(c)}">${esc(c)}</button>`).join("")}</div><div class="bank-select-row">${select("考试","exam",activeExam,exams)}${select("题型","type",activeType,types)}${select("难度","difficulty",activeDifficulty,diffs)}</div>`;$("bankCount").textContent=String(filtered().length)}
function renderQuestion(){const list=filtered();const q=activeQuestion();if(!q)return;selectedOption="";$("practiceExam").textContent=q.examType;$("practiceSubject").textContent=`${q.subject} / ${q.chapter}`;$("practiceProgress").textContent=`${activeIndex+1} / ${list.length||1}`;$("practiceTitle").textContent=`${q.category} · ${q.type||"单选题"} · ${q.difficulty}`;$("practiceStem").textContent=q.stem;document.getElementById("practiceSource")?.remove();$("practiceStem").insertAdjacentHTML("afterend",`<div class="source-note" id="practiceSource">来源：${esc(q.sourceType)} · ${esc(q.licenseNote)}</div>`);$("optionList").innerHTML=q.options.map((op,i)=>`<button class="option-btn" type="button" data-option="${String.fromCharCode(65+i)}"><strong>${String.fromCharCode(65+i)}</strong><span>${esc(op)}</span></button>`).join("");$("practiceExplain").classList.add("hidden");$("practiceExplain").innerHTML="";icons()}

function parseCsv(text){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<text.length;i++){const c=text[i],n=text[i+1];if(c==='"'&&quoted&&n==='"'){cell+='"';i++}else if(c==='"')quoted=!quoted;else if(c===","&&!quoted){row.push(cell);cell=""}else if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&n==="\n")i++;row.push(cell);if(row.some(v=>v.trim()))rows.push(row);row=[];cell=""}else cell+=c}row.push(cell);if(row.some(v=>v.trim()))rows.push(row);const headers=rows.shift()?.map(h=>h.trim())||[];return rows.map(values=>Object.fromEntries(headers.map((h,i)=>[h,values[i]||""])))}
async function parseImportFile(file){const text=await file.text();if(file.name.toLowerCase().endsWith(".csv"))return parseCsv(text);const data=JSON.parse(text);return Array.isArray(data)?data:data.questions||[]}
function renderImportSummary(){const imported=getImported();if($("importedCount"))$("importedCount").textContent=String(imported.length);if($("importPreview"))$("importPreview").innerHTML=imported.slice(0,5).map(q=>`<article class="import-item"><strong>${esc(q.examType)} · ${esc(q.subject)}</strong><p>${esc((q.stem||"").slice(0,60))}</p><span>${esc(q.sourceType)} / ${esc(q.licenseNote)}</span></article>`).join("")}
async function importQuestions(){const file=$("questionImportFile")?.files?.[0];if(!file)return toast("请先选择题库文件");try{const raw=await parseImportFile(file);const valid=[],errors=[];raw.forEach((item,i)=>{const q=normalize(item,i);const miss=validate(q);if(miss.length)errors.push(`第 ${i+1} 题：${miss.join("、")}`);else valid.push(q)});if(errors.length){$("importStatus").textContent=`导入失败：${errors.slice(0,3).join("；")}`;return toast("题库校验未通过")}const merged=getImported();valid.forEach(q=>{const i=merged.findIndex(x=>x.id===q.id);if(i>=0)merged[i]=q;else merged.push(q)});setImported(merged);await loadBank();$("importStatus").textContent=`导入成功：新增/更新 ${valid.length} 道题。`;toast("题库导入成功")}catch(e){$("importStatus").textContent=`导入失败：${e.message}`;toast("导入失败，请检查文件格式")}}
async function publishServerBank(){const imported=getImported();const token=($("adminTokenInput")?.value||"").trim();if(!imported.length)return toast("请先导入题库文件");if(!token){$("importStatus").textContent="发布前需要填写管理员口令。";return toast("请填写管理员口令")}try{$("importStatus").textContent="正在发布到服务器，请稍等...";const res=await fetch("/api/question-bank",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,questions:imported})});const payload=await res.json().catch(()=>({}));if(!res.ok)throw new Error(payload.error||"发布失败");await loadBank();$("importStatus").textContent=`发布成功：本次发布 ${payload.imported} 道，服务器题库共 ${payload.total} 道。`;toast("题库已发布到服务器")}catch(e){$("importStatus").textContent=`发布失败：${e.message}`;toast("发布失败，请检查管理员口令或服务器配置")}}
async function refreshServerBank(){await loadBank();$("importStatus").textContent=`已刷新云端题库：服务器题库 ${serverQuestions.length} 道。`;toast("云端题库已刷新")}
function downloadFile(name,content,type="application/json;charset=utf-8"){const blob=new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function downloadTemplate(){downloadFile("question-bank-template.json",JSON.stringify({version:"0.6.0",questions:[normalize({id:"cet4-demo-001",category:"英语类",examType:"大学英语四级",subject:"英语-词汇语法",chapter:"核心词汇",knowledgePoint:"动词辨析",type:"单选题",difficulty:"基础",stem:"The university plans to ______ more scholarships.",options:["provide","prevent","pretend","prefer"],answer:"A",explanation:"provide scholarships 表示提供奖学金。",sourceType:"自建题库",source:"自建原创题",licenseNote:"原创题，可用于当前产品训练。"})]},null,2));toast("题库模板已下载")}
function exportBank(){downloadFile("ai-exam-coach-question-bank.json",JSON.stringify({version:"0.6.0",questions:questionBank},null,2));toast("当前题库已导出")}
function clearImported(){if(!confirm("确定清空本机导入题库吗？"))return;localStorage.removeItem(IMPORT_KEY);loadBank();toast("导入题库已清空")}

function collect(){return{examType:$("examType").value,subject:$("subject").value,question:$("question").value.trim(),myAnswer:$("myAnswer").value.trim(),correctAnswer:$("correctAnswer").value.trim(),thinking:$("thinking").value.trim(),focuses:Array.from(document.querySelectorAll("#focuses input:checked")).map(x=>x.value)}}
function localMd(data,reason=""){return`## 本地备用诊断\n${reason?`备用原因：${reason}\n`:""}\n## 初步判断\n- 考试类型：${data.examType}\n- 科目模块：${data.subject}\n- 我的答案：${data.myAnswer||"未填写"}\n- 正确答案：${data.correctAnswer||"未提供"}\n\n## 思维评价\n请重点检查题干条件是否完整转化，是否把可能为真误当成一定为真，是否混淆概念定义。\n\n## 纠正方法\n1. 先把题干条件逐条翻译成逻辑关系或关键词。\n2. 再用已知条件排除不可能选项。\n3. 最后只选择“一定成立”的结论。`}
function mdHtml(md){return md.split(/\r?\n/).map(line=>{const t=line.trim();if(!t)return"";if(t.startsWith("## "))return`<h2>${esc(t.slice(3))}</h2>`;if(/^[-*]\s+/.test(t))return`<li>${esc(t.replace(/^[-*]\s+/,""))}</li>`;if(/^\d+\.\s+/.test(t))return`<li>${esc(t.replace(/^\d+\.\s+/,""))}</li>`;return`<p>${esc(t)}</p>`}).join("")}
function renderMd(md,mode,reason=""){latestMarkdown=md;$("score").textContent=mode==="ai"?"AI":"备";$("scoreLabel").textContent=mode==="ai"?"智能诊断":"本地备用";$("generatedAt").textContent=`${mode==="ai"?"AI 已诊断":"本地备用已生成"}：${new Date().toLocaleString("zh-CN",{hour12:false})}`;$("result").innerHTML=`<section class="result-section"><div class="tagline"><span class="tag">${mode==="ai"?"AI 思维诊断":"本地备用生成"}</span>${reason?`<span class="tag">备用原因：${esc(reason)}</span>`:""}</div></section><section class="result-section"><div class="markdown-result">${mdHtml(md)}</div></section><section class="result-section"><button class="btn primary" type="button" id="copyBtn"><i data-lucide="copy"></i> 复制诊断</button></section>`;$("copyBtn").onclick=async()=>{await navigator.clipboard.writeText(latestMarkdown);toast("诊断结果已复制")};icons()}
async function callAi(data){const res=await fetch("/api/generate-plan",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(data)});const payload=await res.json().catch(()=>({}));if(!res.ok)throw new Error(payload.error||"AI 接口调用失败");return payload}
async function diagnose(){const data=collect();if(!data.question)return toast("请先粘贴题目内容");if(!data.thinking)return toast("请写下你的做题思路");$("score").textContent="...";$("scoreLabel").textContent="诊断中";try{const payload=await callAi(data);renderMd(payload.markdown||"","ai");saveRecord(data,payload.markdown||"","ai")}catch(e){const md=localMd(data,e.message);renderMd(md,"local",e.message);saveRecord(data,md,"local")}}
function saveRecord(data,markdown,mode){const list=JSON.parse(localStorage.getItem(RECORD_KEY)||"[]");list.unshift({createdAt:new Date().toISOString(),data,markdown,mode,status:data.correctAnswer&&data.myAnswer&&data.correctAnswer.toLowerCase()===data.myAnswer.toLowerCase()?"correct":"mistake"});localStorage.setItem(RECORD_KEY,JSON.stringify(list.slice(0,80)));renderRecords()}
function renderRecords(){const list=JSON.parse(localStorage.getItem(RECORD_KEY)||"[]");$("totalCount").textContent=String(list.length);$("mistakeCount").textContent=String(list.filter(r=>r.status==="mistake").length);$("lastSubject").textContent=list[0]?.data?.subject||"--";const item=r=>`<article class="record-item"><div><div class="record-title">${esc((r.data.question||"未命名题目").slice(0,44))}</div><div class="record-meta"><span>${esc(r.data.examType)}</span><span>${esc(r.data.subject)}</span><span>${new Date(r.createdAt).toLocaleString("zh-CN",{hour12:false})}</span></div></div><div class="record-actions"><span class="record-status ${r.status}">${r.status==="mistake"?"待复盘":"已正确"}</span></div></article>`;$("historyList").innerHTML=list.length?list.slice(0,12).map(item).join(""):'<div class="record-empty">还没有诊断记录。</div>';const mistakes=list.filter(r=>r.status==="mistake");$("mistakeList").innerHTML=mistakes.length?mistakes.map(item).join(""):'<div class="record-empty">当前没有待复盘错题。</div>'}
async function generateSimilar(){const q=activeQuestion();const data={examType:q.examType,subject:q.subject,question:`请基于以下题目的知识点，原创生成 3 道同类训练题，不要照搬题干和选项。\n\n原题：${q.stem}\n选项：${q.options.join(" / ")}\n正确答案：${q.answer}\n解析：${q.explanation}`,myAnswer:"",correctAnswer:"",thinking:"请生成同类训练题，并标注每题答案、解析、知识点、难度和版权说明：AI 原创训练题，仅作练习参考。",focuses:["相似题训练建议","知识点定位"]};try{const payload=await callAi(data);renderMd(payload.markdown||"","ai")}catch(e){renderMd(localMd(data,e.message),"local",e.message)}}
function applySample(key){const s=samples[key];if(!s)return;[$("examType").value,$("subject").value,$("question").value,$("myAnswer").value,$("correctAnswer").value,$("thinking").value]=s;document.querySelectorAll(".template-btn").forEach(b=>b.classList.toggle("active",b.dataset.template===key))}
function bind(){
  $("bankFilters").addEventListener("click",e=>{const b=e.target.closest("[data-category]");if(!b)return;activeCategory=b.dataset.category;activeExam="全部";activeType="全部";activeDifficulty="全部";activeIndex=0;renderFilters();renderQuestion()});
  $("bankFilters").addEventListener("change",e=>{const s=e.target.closest("[data-filter]");if(!s)return;if(s.dataset.filter==="exam")activeExam=s.value;if(s.dataset.filter==="type")activeType=s.value;if(s.dataset.filter==="difficulty")activeDifficulty=s.value;activeIndex=0;renderFilters();renderQuestion()});
  $("optionList").addEventListener("click",e=>{const b=e.target.closest("[data-option]");if(!b)return;selectedOption=b.dataset.option;document.querySelectorAll(".option-btn").forEach(x=>x.classList.toggle("selected",x===b))});
  $("checkAnswerBtn").onclick=()=>{const q=activeQuestion();if(!selectedOption)return toast("请先选择一个答案");document.querySelectorAll(".option-btn").forEach(b=>{b.classList.toggle("correct",b.dataset.option===q.answer);b.classList.toggle("wrong",b.dataset.option===selectedOption&&selectedOption!==q.answer)});$("practiceExplain").classList.remove("hidden");$("practiceExplain").innerHTML=`<strong>${selectedOption===q.answer?"答对了":"这题需要复盘"}</strong><p>正确答案：${esc(q.answer)}</p><p>${esc(q.explanation)}</p>`};
  $("nextQuestionBtn").onclick=()=>{activeIndex=(activeIndex+1)%Math.max(filtered().length,1);renderQuestion()};
  $("sendToCoachBtn").onclick=()=>{const q=activeQuestion();$("examType").value=q.examType;$("subject").value=q.subject;$("question").value=`${q.stem}\n${q.options.map((op,i)=>`${String.fromCharCode(65+i)}. ${op}`).join("\n")}`;$("myAnswer").value=selectedOption;$("correctAnswer").value=q.answer;$("thinking").value=selectedOption?`我在题库练习中选择了 ${selectedOption}，请帮我判断知识点、解题路径和容易出错的地方。`:"我还没有作答，想先让 AI 讲清楚这道题的知识点和解题方法。";scrollTo({top:0,behavior:"smooth"})};
  $("generateSimilarBtn").onclick=generateSimilar;$("importQuestionsBtn").onclick=importQuestions;$("downloadTemplateBtn").onclick=downloadTemplate;$("exportBankBtn").onclick=exportBank;$("clearImportedBankBtn").onclick=clearImported;$("publishServerBankBtn").onclick=publishServerBank;$("refreshServerBankBtn").onclick=refreshServerBank;
  $("questionImportFile").onchange=()=>{const file=$("questionImportFile").files?.[0];$("importStatus").textContent=file?`已选择：${file.name}`:"等待选择题库文件。"};
  $("coachForm").addEventListener("submit",e=>{e.preventDefault();diagnose()});document.querySelectorAll(".template-btn").forEach(b=>b.onclick=()=>applySample(b.dataset.template));$("resetBtn").onclick=()=>applySample("civil");$("sampleBtn").onclick=()=>applySample(["civil","public","teacher","essay"][Math.floor(Math.random()*4)]);
  document.querySelectorAll(".record-tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".record-tab").forEach(x=>x.classList.toggle("active",x===b));$("historyList").classList.toggle("hidden",b.dataset.recordTab!=="history");$("mistakeList").classList.toggle("hidden",b.dataset.recordTab!=="mistakes")});
  $("exportRecordsBtn").onclick=()=>toast("学习记录导出将在云端档案版本增强");$("clearRecordsBtn").onclick=()=>{localStorage.removeItem(RECORD_KEY);renderRecords();toast("学习记录已清空")}
}

injectV6();bind();renderMd(localMd(collect()),"local");renderRecords();loadBank();icons();
